### 제품 가져오기
GET {{backend}}:{{productPort}}/products
Accept: application/json

### 제품 저장
POST {{backend}}:{{productPort}}/products
Content-Type: application/json

{
  "name": "product",
  "price": 20.0,
  "quantity": 10
}

### 제품 상세
GET {{backend}}:{{productPort}}/products/01GN72X9D2AR3SJHGZ4XAWMWTW
Accept: application/json

### 제품 삭제
DELETE {{backend}}:{{productPort}}/products/01GMQCAM3W5H6XZJDZE3SP9TEN
